import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { GetGreeter, SetGreeter } from '../components/contract';
import { useBalance } from 'wagmi'


export default function Home() {

  const { data, isError, isLoading } = useBalance({
    address: '0x765374f6E28879cC3f75138e008c0f2AB9Dbe1D9',
  })
 
  
  return (
    <div className={''}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ padding: '1rem' }}>
        <ConnectButton />
      </header>

      <main
        style={{
          minHeight: '60vh',
          flex: '1',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        {/* <GetGreeter />
        <SetGreeter /> */}
        Hello World
        {data?.formatted} {data?.symbol}

      </main>
    </div>
  );
}
